@'
apiVersion: v1
kind: Secret
metadata:
  name: weather-api-secret
type: Opaque
data:
  api-key: NWJmMDM3NDVkODM3NzAwNzQzZTkyOWYzYzQ3ZTIxZTQ=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-backend
  labels:
    app: weather-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-backend
  template:
    metadata:
      labels:
        app: weather-backend
    spec:
      containers:
      - name: weather-backend
        image: cst8918weatheracr.azurecr.io/weather-backend:v2
        ports:
        - containerPort: 3000
        env:
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-key
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PASSWORD
          value: ""
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: weather-backend-service
spec:
  selector:
    app: weather-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
'@ | Set-Content .\k8s\backend-deployment.yaml
